steps:
  # build container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcpdevops', '.']
  # push container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/gcpdevops']  
  # deploy container image to GKE
- name: 'gcr.io/cloud-builders/gke-deploy'
  args: 
  - run
  - --filename=gke.yaml
  - --image=gcr.io/$PROJECT_ID/gcpdevops
  - --location=us-central1 # the location of your GKE cluster
  - --cluster=gcp-devops-gke # the name of your GKE cluster
  - --namespace=gcp-devops-prod